apply plugin: "com.android.application"

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.xiimmortal.game"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 3
        versionName "0.2.3"
    }
    signingConfigs {
        debug {
            storeFile file(System.getProperty("user.home") + "/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
        release {
            storeFile file(System.getProperty("user.home") + "/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
