apply plugin: "com.android.application"

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.xiimmortal.game"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 2
        versionName "0.2.1"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
